services:
  ghost-blog:
    image: ghost:5-alpine
    container_name: ghost-blog
    restart: unless-stopped
    env_file: .env
    environment:
      # Updated to your requested root domain
      - url=https://choukalos.com
      - server__trustProxy=true
      - MODE_ENV=production
      - portal__protocls=https
      - database__client=mysql
      - database__connection__host=172.17.0.1
      - database__connection__user=${GHOST_DB_USER}
      - database__connection__password=${GHOST_DB_PASS}
      - database__connection__database=${GHOST_DB_NAME}
    volumes:
      - ../data/ghost:/var/lib/ghost/content
    networks:
      - public-net

  cloudflared-web:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-web
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - public-net

networks:
  public-net:
    name: public-net


