"""Structured state for the demo workflow coordinator.

Each field carries only what the next phase needs from prior phases,
keeping per-invocation context well under 30K tokens.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class DemoState(BaseModel):
    """Pass-through state between per-phase agent invocations.

    The coordinator (run_demo) instantiates this once and mutates it
    as each phase completes, feeding only the relevant fields into
    the next phase's prompt.
    """

    raw_prompt: str = Field(
        ...,
        description="The original user prompt describing the demo to build.",
    )
    thread_id: str = Field(
        "",
        description="Thread ID used for checkpoint persistence / resumption.",
    )

    # ── Phase 1 output ─────────────────────────────────────────────
    title: str = Field(
        "",
        description="Demo title (generated by Phase 1 or provided by user).",
    )
    parsed_requirements: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured brief from Phase 1: description, audience, features, screens, style hints.",
    )

    # ── Phase 2 output ─────────────────────────────────────────────
    kb_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Knowledge base lookup results from Phase 2.",
    )

    # ── Phase 3 output ─────────────────────────────────────────────
    research_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Web research findings from Phase 3 (competitor analysis, UX patterns, etc.).",
    )

    # ── Phase 4 output ─────────────────────────────────────────────
    design_spec: str = Field(
        "",
        description="Full requirements + visual design specification from Phase 4.",
    )
    discovery_notes: dict[str, Any] = Field(
        default_factory=dict,
        description="Product discovery insights from Phase 4: mvp_features, nice_to_have, research_insights.",
    )

    # ── Phase 5 output ─────────────────────────────────────────────
    build_plan: dict[str, Any] = Field(
        default_factory=dict,
        description="Numbered build plan from Phase 5 with functional acceptance criteria per step.",
    )
    complexity_score: int = Field(
        default=0,
        description="Complexity score 1-10 computed in Phase 5.",
    )
    complexity_breakdown: dict[str, Any] = Field(
        default_factory=dict,
        description="Complexity breakdown from Phase 5: screen_count, interactive_elements, mocked_features, estimated_build_effort.",
    )

    # ── Phase 6 output ─────────────────────────────────────────────
    current_html: str = Field(
        "",
        description="Current HTML content after the build loop (Phase 6).",
    )

    # ── Phase 7 output ─────────────────────────────────────────────
    verification_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Results from verify_interactivity: score, verified_interactions, issues, mocked_features.",
    )

    # ── Phase 8 output ─────────────────────────────────────────────
    critique_results: dict[str, Any] = Field(
        default_factory=dict,
        description="Results from critique_demo: overall_score, issues_found, strengths.",
    )

    # ── Phase 9 output ─────────────────────────────────────────────
    final_html: str = Field(
        "",
        description="Final polished HTML after all phases complete.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Complete metadata dict written to metadata.json by Phase 9.",
    )

    def to_dict(self) -> dict:
        """Serialize the full state to a plain dict for checkpoint persistence."""
        return self.model_dump(mode="json")

    def to_json(self) -> str:
        """Serialize the full state to a JSON string for cross-phase passing."""
        return self.model_dump_json()

    @classmethod
    def from_dict(cls, data: dict) -> "DemoState":
        """Deserialize state from a plain dict (e.g. from a checkpoint file)."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, data: str) -> "DemoState":
        """Deserialize state from a JSON string."""
        return cls.model_validate_json(data)
