"""
Generate and update index.md files and mkdocs.yml navigation
for the Family Knowledge Base wiki.

Scans all processed markdown files under KB_ROOT, writes per-category
category indexes with short summaries and links, writes a root index,
and regenerates the mkdocs.yml nav section so every file is reachable.
"""

import re
import yaml
from pathlib import Path
from datetime import datetime

from knowledge.family_kb.config import KB_ROOT

# ---------------------------------------------------------------------------
# MKDocs configuration helpers
# ---------------------------------------------------------------------------

DEFAULT_MKDOCS_YAML = KB_ROOT.parent / "mkdocs.yml"

CATEGORIES_IN_ORDER = [
    "family",
    "finances",
    "games",
    "guitar",
    "house",
    "investments",
    "research",
    "travel",
    "vehicles",
]


def _discover_categories() -> list[str]:
    """Return sorted list of top-level directories that contain .md files."""
    categories = set()
    for md in KB_ROOT.rglob("*.md"):
        rel = md.relative_to(KB_ROOT)
        parts = rel.parts
        if len(parts) >= 2 and parts[0] != "index.md":
            categories.add(parts[0])
        elif len(parts) == 1 and rel.name != "index.md":
            # top-level orphans – put under "root"
            categories.add("root")
    ordered = []
    for cat in CATEGORIES_IN_ORDER:
        if cat in categories:
            ordered.append(cat)
            categories.discard(cat)
    # any discovered categories not in the default order go at the end
    ordered.extend(sorted(categories))
    return ordered


# ---------------------------------------------------------------------------
# Summary generation (local, no LLM dependency)
# ---------------------------------------------------------------------------

def _extract_summary(text: str, max_words: int = 80) -> str:
    """
    Pull a short summary from the top of a markdown document.
    Strips headings / metadata lines and concatenates the first few
    meaningful paragraphs up to *max_words*.
    """
    lines = text.splitlines()
    paragraphs: list[str] = []

    for line in lines:
        stripped = line.strip()
        # skip headings
        if stripped.startswith("#"):
            continue
        # skip blockquotes / metadata
        if stripped.startswith(">"):
            continue
        # skip horizontal rules, empty lines
        if not stripped or stripped == "---" or stripped == "***":
            continue

        if paragraphs:
            # accumulate into current paragraph
            paragraphs[-1] += " " + stripped
        else:
            paragraphs.append(stripped)

        word_count = sum(len(p.split()) for p in paragraphs)
        if word_count >= max_words:
            break

    summary = " ".join(paragraphs)

    # If nothing useful was found, use the first H1 title
    if not summary.strip():
        for line in lines:
            m = re.match(r"^#\s+(.+)$", line.strip())
            if m:
                return m.group(1).strip()
        return "_No summary available_"

    # Trim to max_words
    words = summary.split()
    if len(words) > max_words:
        summary = " ".join(words[:max_words]) + " ..."

    return summary.strip()


# ---------------------------------------------------------------------------
# Markdown link helpers
# ---------------------------------------------------------------------------

def _mk_link(rel_path: str, label: str | None = None) -> str:
    rel = rel_path.replace("\\", "/")
    label = label or rel_path
    return f"[{label}]({rel})"


def _human_name(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").title()


# ---------------------------------------------------------------------------
# Core generation
# ---------------------------------------------------------------------------

def _scan_files(category: str) -> list[tuple[Path, str, str]]:
    """Return list of (abs_path, rel_path, summary) for a given category."""
    results = []
    cat_dir = KB_ROOT / category if category != "root" else KB_ROOT
    if not cat_dir.exists():
        return results

    for md in sorted(cat_dir.rglob("*.md")):
        rel = md.relative_to(KB_ROOT).as_posix()
        # skip index files in this scan – they are generated by us
        if md.name == "index.md":
            continue
        text = md.read_text(errors="ignore")
        summary = _extract_summary(text)
        results.append((md, rel, summary))
    return results


def generate_root_index() -> str:
    """Generate the root index.md content."""
    lines = [
        "# Family Knowledge Base",
        "",
        "> Auto-generated by AI Harness. Last updated: "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    categories = _discover_categories()

    for cat in categories:
        cat_rel = cat if cat != "root" else ""
        index_link = f"{cat}/index.md" if cat != "root" else f"{cat_rel}index.md"
        label = _human_name(cat) if cat != "root" else "Other"
        lines.append(f"- **[{label}]({index_link.replace(chr(92), '/')})**")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Also list every non-index file at root level for quick access
    for md in sorted(KB_ROOT.glob("*.md")):
        if md.name == "index.md":
            continue
        summary = _extract_summary(md.read_text(errors="ignore"))
        lines.append(f"- [{md.stem}](./{md.name}) - {summary}")

    return "\n".join(lines)


def generate_category_index(category: str) -> str:
    """Generate an index.md for a single category directory."""
    title = _human_name(category) if category != "root" else "Other Documents"
    lines = [
        f"# {title}",
        "",
        "> Auto-generated by AI Harness. Last updated: "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    files = _scan_files(category)
    if not files:
        lines.append("_No documents in this category yet._")
        lines.append("")
        lines.append("Drop files into the raw folder to add content here.")
        return "\n".join(lines)

    for _, rel_path, summary in files:
        label = _human_name(Path(rel_path).stem)
        # Make link relative to the index.md's own directory
        leaf = Path(rel_path).name
        lines.append(f"- **[{label}]({leaf})**")
        lines.append(f"  - {summary}")
        lines.append("")

    return "\n".join(lines)


def generate_mkdocs_nav() -> list:
    """Return a nav list suitable for mkdocs.yml."""
    categories = _discover_categories()
    nav = [{"Family Knowledge Base": "index.md"}]

    for cat in categories:
        cat_dir = KB_ROOT / cat if cat != "root" else KB_ROOT
        label = _human_name(cat) if cat != "root" else "Other"

        if not cat_dir.exists() or not list(cat_dir.rglob("*.md")):
            nav.append({label: f"{cat}/index.md"})
            continue

        cat_index = "index.md" if cat == "root" else f"{cat}/index.md"
        entries: list = [{label: cat_index}]

        for md in sorted(cat_dir.rglob("*.md")):
            rel = md.relative_to(cat_dir).as_posix()
            if md.name == "index.md":
                continue
            stem = _human_name(md.stem)
            rel_link = rel.replace("\\", "/")
            if cat != "root":
                rel_link = f"{cat}/{rel_link}"
            entries.append({stem: rel_link})

        nav.append({label: entries})

    return nav


def _write_mkdocs() -> Path:
    """Rewrite mkdocs.yml with updated nav while preserving plugins/theme."""
    mkdocs_path = DEFAULT_MKDOCS_YAML
    if not mkdocs_path.exists():
        mkdocs_path = KB_ROOT / "mkdocs.yml"

    # Read existing to preserve any custom settings
    existing_cfg: dict = {}
    if mkdocs_path.exists():
        try:
            existing_cfg = yaml.safe_load(mkdocs_path.read_text()) or {}
        except Exception:
            pass

    nav = generate_mkdocs_nav()
    existing_cfg.setdefault("site_name", "Family Knowledge Base")
    existing_cfg.setdefault("theme", {"name": "material"})
    existing_cfg["nav"] = nav

    # Preserve plugins if present
    if "plugins" not in existing_cfg:
        existing_cfg.setdefault("plugins", [{"search": None}])

    # Persist extra config in markdown_extensions or any user keys — leave as-is

    mkdocs_path.write_text(yaml.dump(existing_cfg, default_flow_style=False), encoding="utf-8")
    return mkdocs_path


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def regenerate_all() -> dict:
    """
    Regenerate every index.md and the mkdocs.yml nav.
    Returns a summary dict.
    """
    categories = _discover_categories()
    stats = {
        "categories": categories,
        "category_indexes": 0,
        "root_index": False,
        "mkdocs_updated": False,
        "files": {},
    }

    # Root index
    root_index = KB_ROOT / "index.md"
    root_index.write_text(generate_root_index(), encoding="utf-8")
    stats["root_index"] = True

    # Per-category indexes
    for cat in categories:
        cat_dir = KB_ROOT / cat if cat != "root" else KB_ROOT
        cat_dir.mkdir(parents=True, exist_ok=True)
        index_path = cat_dir / "index.md"
        index_path.write_text(generate_category_index(cat), encoding="utf-8")
        stats["category_indexes"] += 1
        files_in_cat = len(_scan_files(cat))
        # Include counts per category
        if cat != "root":
            stats["files"][cat] = files_in_cat

    # Regenerate mkdocs nav
    try:
        mkdocs_path = _write_mkdocs()
        stats["mkdocs_updated"] = True
        stats["mkdocs_path"] = str(mkdocs_path)
    except Exception as exc:
        stats["mkdocs_updated"] = False
        stats["mkdocs_error"] = str(exc)

    return stats
